import { env } from 'cloudflare:workers';
import catalog from '@/data/events.json';
import { emptyState,applyDoc,summarize,sandboxDocs,expire } from '@/lib/events.mjs';
const headers={'Cache-Control':'no-store'};
const reply=(b:unknown,status=200,cookie?:string)=>Response.json(b,{status,headers:{...headers,...(cookie?{'Set-Cookie':cookie}:{})}});
function scope(req:Request){const match=req.headers.get('cookie')?.match(/(?:^|;\s*)event_workspace=([a-f0-9-]{36})(?:;|$)/);const id=match?.[1]||crypto.randomUUID();return {id,cookie:match?undefined:`event_workspace=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=2592000${new URL(req.url).protocol==='https:'?'; Secure':''}`};}
async function read(req:Request){const {id,cookie}=scope(req);const mode=new URL(req.url).searchParams.get('mode')==='sandbox'?'sandbox':'verified';const key=id+':'+mode;const db=env.DB;if(!db)throw new Error('database-unavailable');let row=await db.prepare('SELECT state, revision FROM event_workspaces WHERE id = ?').bind(key).first<{state:string;revision:number}>();if(!row){let state=emptyState();if(mode==='verified')state=applyDoc(state,catalog.docs[0]).state;await db.prepare('INSERT OR IGNORE INTO event_workspaces (id,state,revision,updated_at) VALUES (?,?,?,?)').bind(key,JSON.stringify(state),0,new Date().toISOString()).run();row=await db.prepare('SELECT state, revision FROM event_workspaces WHERE id = ?').bind(key).first<{state:string;revision:number}>();}if(!row)throw new Error('database-unavailable');return {db,key,cookie,mode,state:JSON.parse(row.state),revision:row.revision};}
function view(r:Awaited<ReturnType<typeof read>>,extra:Record<string,unknown>={}){return {...r.state,revision:r.revision,mode:r.mode,events:summarize(r.state),catalog:r.mode==='sandbox'?sandboxDocs():catalog.docs,dataVersion:catalog.version,...extra};}
export async function GET(req:Request){try{const r=await read(req);return reply(view(r),200,r.cookie);}catch{return reply({error:'事件数据库暂不可用，请重试；没有展示虚构的已保存结果。'},503);}}
export async function POST(req:Request){try{if(Number(req.headers.get('content-length')||0)>14000)return reply({error:'请求过大'},413);const raw=await req.text();if(raw.length>14000)return reply({error:'请求过大'},413);const input=JSON.parse(raw);const r=await read(req);if(input.revision!==r.revision)return reply({error:'内容已在另一页面更新，请刷新后重试。'},409,r.cookie);let state=structuredClone(r.state);let extra={};
 switch(input.action){
 case 'ingest':{const doc=(r.mode==='sandbox'?sandboxDocs():catalog.docs).find(d=>d.id===input.id);if(!doc)return reply({error:'证据ID无效'},400);const result=applyDoc(state,doc);state=result.state;extra={duplicate:result.duplicate,changed:result.changed};break;}
 case 'watch':if(typeof input.value!=='boolean')return reply({error:'关注参数无效'},400);state.watch=input.value;break;
 case 'read':state.notifications=state.notifications.map((n:{id:string;read:boolean})=>input.id===n.id?{...n,read:true}:n);break;
 case 'expire':if(r.mode!=='sandbox')return reply({error:'真实历史证据不以模拟时钟修改'},400);state=expire(state,input.asOf);break;
 case 'custom':{const d=input.doc;if(!d||/买入|卖出|目标价|稳赚|必涨/.test(JSON.stringify(d))||typeof d.quote!=='string'||d.quote.length>240||typeof d.summary!=='string'||d.summary.length>240||!['事实','观点','推测','传闻'].includes(d.kind)||!/^\d{6}$/.test(d.company||'')||!['回购','扩建','其他'].includes(d.eventType)||!/^\d{4}-\d{2}-\d{2}$/.test(d.anchor||''))return reply({error:'请先检查AI提取并补全原始计划日期'},400);state=applyDoc(state,{id:'U-'+crypto.randomUUID(),company:d.company,eventType:d.eventType,anchor:d.anchor,title:d.summary,kind:d.kind,quote:d.quote,claims:{待核验陈述:d.summary},verified:false,weight:0,source:'用户提交 · 尚未核验',url:null,occurredAt:null,disclosedAt:null,timePrecision:'原披露时间未知；入库时间不替代披露时间',collectedAt:null,note:'接收日期仅用于编排；不能替代真实披露时间。AI分类不能赋予权威性。'}).state;break;}
 default:return reply({error:'操作无效'},400);}
 const updated=await r.db.prepare('UPDATE event_workspaces SET state=?,revision=revision+1,updated_at=? WHERE id=? AND revision=?').bind(JSON.stringify(state),new Date().toISOString(),r.key,r.revision).run();if(!updated.meta.changes)return reply({error:'并发更新冲突，请刷新后重试。'},409,r.cookie);r.state=state;r.revision++;return reply(view(r,extra),200,r.cookie);
 }catch(e){const msg=e instanceof Error?e.message:'';return reply({error:msg==='评估日期无效'||msg==='评估日期不能倒退'||msg==='证据包已达上限'?msg:'请求失败，上一版已保留。'},msg==='database-unavailable'?503:400);}}
