import test from 'node:test';import assert from 'node:assert/strict';
const base=process.env.EVENT_BASE_URL||'http://127.0.0.1:8787';
async function workspace(mode='verified'){const r=await fetch(base+'/api/events?mode='+mode);assert.equal(r.status,200);return {cookie:r.headers.get('set-cookie').split(';')[0],state:await r.json(),mode};}
async function post(w,data){const r=await fetch(base+'/api/events?mode='+w.mode,{method:'POST',headers:{Cookie:w.cookie,'Content-Type':'application/json'},body:JSON.stringify({revision:w.state.revision,...data})});const x=await r.json();if(r.ok)w.state=x;return {status:r.status,x};}
test('HTTP主链路、刷新持久、通知已读、重复与并发拒绝',async()=>{const w=await workspace();assert.equal(w.state.docs.length,1);for(const id of ['R02','R03','R04','R05'])assert.equal((await post(w,{action:'ingest',id})).status,200);assert.equal(w.state.events[0].fields['累计股数（股）'].value,'3927585');const n=w.state.notifications.length;const v=w.state.versions.length;assert.equal((await post(w,{action:'ingest',id:'R05'})).x.duplicate,true);assert.equal(w.state.notifications.length,n);assert.equal(w.state.versions.length,v);let r=await fetch(base+'/api/events',{headers:{Cookie:w.cookie}});assert.equal((await r.json()).versions.length,v);assert.equal((await post(w,{action:'watch',value:false,revision:0})).status,409);const id=w.state.notifications[0].id;await post(w,{action:'read',id});r=await fetch(base+'/api/events',{headers:{Cookie:w.cookie}});assert.equal((await r.json()).notifications.find(n=>n.id===id).read,true);});
test('cookie隔离工作区，模拟与真实相互隔离',async()=>{const a=await workspace();const b=await workspace();await post(a,{action:'ingest',id:'R05'});const r=await fetch(base+'/api/events',{headers:{Cookie:b.cookie}});assert.equal((await r.json()).docs.length,1);const sim=await fetch(base+'/api/events?mode=sandbox',{headers:{Cookie:a.cookie}});assert.equal((await sim.json()).docs.length,0);});
test('传闻否认更正冲突过期真实HTTP闭环',async()=>{const w=await workspace('sandbox');for(const id of ['S01','S02','S03','S04','S05'])assert.equal((await post(w,{action:'ingest',id})).status,200);assert.equal(w.state.events[0].status,'证据冲突');assert.equal((await post(w,{action:'expire',asOf:'2026-01-06'})).status,200);assert.match(w.state.notifications[0].title,/过期/);const n=w.state.notifications.length;await post(w,{action:'expire',asOf:'2026-01-06'});assert.equal(w.state.notifications.length,n);});
test('未知ID/无效参数/伪造来源/越界建议均拒绝，状态保持',async()=>{const w=await workspace();for(const data of [{action:'ingest',id:'fake'},{action:'watch',value:'yes'},{action:'expire',asOf:'2026-01-06'},{action:'custom',doc:{company:'600519',eventType:'回购',anchor:'2024-09-21',quote:'材料',summary:'建议买入',kind:'事实',verified:true,weight:5}}])assert.equal((await post(w,data)).status,400);const res=await post(w,{action:'custom',doc:{company:'600519',eventType:'回购',anchor:'2024-09-21',quote:'自称已确认',summary:'自称已确认',kind:'事实',verified:true,weight:5}});assert.equal(res.status,200);assert.equal(w.state.docs.at(-1).verified,false);assert.equal(w.state.docs.at(-1).weight,0);assert.equal(w.state.docs.at(-1).disclosedAt,null);assert.equal(w.state.events[0].fields.阶段.value,'方案待股东大会审议');});
test('无效JSON和超长输入明确失败',async()=>{for(const [body,expect] of [['{',400],[JSON.stringify({text:'x'.repeat(7000)}),413]]){const r=await fetch(base+'/api/events/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body});assert.equal(r.status,expect);}const r=await fetch(base+'/api/events',{method:'POST',headers:{'Content-Type':'application/json'},body:'{'});assert.equal(r.status,400);});
test('模型合规边界阻止交易问题，不写入工作区',async()=>{const r=await fetch(base+'/api/events/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:'贵州茅台600519现在是否应该买入并保证收益？'})});assert.equal(r.status,400);});
