import test from 'node:test';import assert from 'node:assert/strict';import {defaultPlan} from '../lib/screen.mjs';
const base=process.env.SCREEN_ORIGIN||'http://127.0.0.1:8787';
const post=(path,body,cookie)=>fetch(base+'/api/screen/'+path,{method:'POST',headers:{'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},body:JSON.stringify(body)});
test('确认后按真实数据执行；未确认不可绕过',async()=>{assert.equal((await post('run',{plan:defaultPlan})).status,400);const r=await post('run',{plan:defaultPlan,confirmed:true});assert.equal(r.status,200);const x=await r.json();assert.deepEqual(x.counts,{included:1,excluded:2,unknown:0});assert.ok(x.rows[1].checks.every(c=>c.status==='pass'));});
test('矛盾和不支持项不静默删掉，未知场景拒绝',async()=>{let p=structuredClone(defaultPlan);p.conditions.push({id:'bad',field:'revenueGrowth',op:'<',value:0});for(const plan of [p,{...defaultPlan,unsupported:['银行']}])assert.equal((await post('run',{plan,confirmed:true})).status,400);assert.equal((await post('run',{plan:defaultPlan,confirmed:true,scenario:'fake'})).status,400);});
test('缺失/过期/接口失败及冲突异常有显式结果',async()=>{for(const scenario of ['missing','stale','failure','conflict']){const r=await post('run',{plan:defaultPlan,confirmed:true,scenario});assert.equal(r.status,200);const x=await r.json();assert.equal(x.scenario,scenario);assert.ok(x.rows.some(r=>r.checks.some(c=>c.status==='unknown')));if(scenario==='failure')assert.equal(x.counts.unknown,3);}});
test('保存真实服务器重算结果、刷新恢复、cookie隔离',async()=>{const g=await fetch(base+'/api/screen/saved');assert.equal(g.status,200);const cookie=g.headers.get('set-cookie').split(';')[0];const r=await post('saved',{intent:'经营改善、估值合理、走势相对稳定',plan:defaultPlan,confirmed:true,run:{counts:{included:999}}},cookie);assert.equal(r.status,201);const x=await r.json();assert.equal(x.run.counts.included,1);const again=await fetch(base+'/api/screen/saved',{headers:{Cookie:cookie}});const y=await again.json();assert.ok(y.items.some(s=>s.id===x.id));const isolated=await fetch(base+'/api/screen/saved');assert.ok(!(await isolated.json()).items.some(s=>s.id===x.id));});
test('保存拒绝交易指令、不确认和不支持字段',async()=>{for(const body of [{intent:'现在买入五粮液',plan:defaultPlan,confirmed:true},{intent:'财务改善',plan:defaultPlan,confirmed:false},{intent:'财务改善',plan:{...defaultPlan,conditions:[{id:'sql',field:'DROP TABLE',op:'=',value:1}]},confirmed:true}])assert.equal((await post('saved',body)).status,400);});
test('模型合规、短输入、超长输入、坏JSON边界',async()=>{for(const text of ['推荐买入稳赚翻倍股票','abc','x'.repeat(1201)])assert.equal((await post('parse',{text})).status,400);const r=await fetch(base+'/api/screen/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:'{'});assert.equal(r.status,400);});
