import test from 'node:test';import assert from 'node:assert/strict';import {readFileSync} from 'node:fs';import {screen,defaultPlan,conflicts,validateProposal,changes,relaxations} from '../lib/screen.mjs';
const data=JSON.parse(readFileSync(new URL('../data/screen.json',import.meta.url)));
test('真实样本执行：五粮液入选，茅台利润不达标，老窖收入利润与波动均不达标',()=>{const r=screen(data,defaultPlan);assert.deepEqual(r.counts,{included:1,excluded:2,unknown:0});assert.equal(r.rows.find(r=>r.name==='五粮液').status,'included');assert.ok(r.rows[0].checks.some(c=>c.field==='profitGrowth'&&c.status==='fail'));assert.equal(r.rows[2].checks.filter(c=>c.status==='fail').length,3);assert.ok(r.rows[1].metrics.values.cfo<0);assert.equal(r.rows[1].metrics.window.returns,60);});
test('只改变利润阈值后新增茅台，其他条件仍约束老窖',()=>{const p=structuredClone(defaultPlan);p.conditions[1].value=-5;const a=screen(data,defaultPlan),b=screen(data,p);assert.deepEqual(changes(a,b).map(d=>d.name),['贵州茅台']);const impact=relaxations(data,defaultPlan,'normal').find(x=>x.id==='c1');assert.equal(impact.result.counts.included,2);});
test('缺失不默认为零/通过；PE缺两家全年利润，故单PE条件无法判定',()=>{let p={logic:'AND',window:60,unsupported:[],conditions:[{id:'pe',field:'pe',op:'<=',value:25}]};const r=screen(data,p);assert.deepEqual(r.counts,{included:1,excluded:0,unknown:2});assert.equal(screen(data,defaultPlan,'missing').rows[1].status,'unknown');});
test('已知不满足足以排除，剩余缺失仍明示',()=>{const p=structuredClone(defaultPlan);p.conditions.push({id:'pe',field:'pe',op:'<=',value:25});const r=screen(data,p);assert.equal(r.rows[2].status,'excluded');assert.ok(r.rows[2].checks.some(c=>c.status==='unknown'));});
test('接口失败/行情过期/字段冲突不会产生正常入选',()=>{assert.equal(screen(data,defaultPlan,'failure').counts.unknown,3);assert.equal(screen(data,defaultPlan,'stale').counts.included,0);assert.equal(screen(data,defaultPlan,'conflict').rows[0].checks[0].status,'unknown');});
test('矛盾、严格边界及负估值上限阻止执行',()=>{const p=structuredClone(defaultPlan);p.conditions.push({id:'bad',field:'revenueGrowth',op:'<',value:0});assert.ok(conflicts(p).length);assert.throws(()=>screen(data,p));for(const op of ['>','<'])assert.ok(conflicts({conditions:[{field:'pb',op,value:2},{field:'pb',op:'=',value:2}]}).length);assert.ok(conflicts({conditions:[{field:'pb',op:'<=',value:-1}]}).length);});
test('未支持意图、越界窗口、NaN、SQL字段与重复条件ID均拒绝',()=>{for(const patch of [{unsupported:['全A']},{window:9},{window:1000},{logic:'OR'},{conditions:[{id:'a',field:'DROP TABLE',op:'=',value:1}]},{conditions:[{id:'a',field:'pb',op:'<=',value:NaN}]},{conditions:[{id:'a',field:'pb',op:'<=',value:2},{id:'a',field:'pb',op:'>=',value:1}]}])assert.throws(()=>screen(data,{...structuredClone(defaultPlan),...patch}));});
test('模型不能编造阈值、原文、指标、窗口；模糊阈值必须标示示例',()=>{const text='收入改善，市净率小于8倍，近20交易日波动稳定';const x={logic:'AND',window:20,conditions:[{field:'pb',op:'<',value:8,quote:'市净率小于8倍'},{field:'revenueGrowth',op:'>=',value:null,quote:'收入改善'}],unsupported:[]};const p=validateProposal(x,text);assert.equal(p.conditions[0].assumption,false);assert.equal(p.conditions[1].assumption,true);for(const patch of [{window:30},{conditions:[{...x.conditions[0],value:10}]},{conditions:[{...x.conditions[0],quote:'没有此原文'}]},{conditions:[{...x.conditions[0],field:'targetPrice'}]}])assert.throws(()=>validateProposal({...x,...patch},text));});
test('零/负净资产、负TTM利润和不足窗口不得计算正常估值波动',()=>{let d=structuredClone(data);d.stocks[0].raw.equity=-1;d.stocks[0].raw.ttmProfit=-1;d.stocks[0].market.bars=d.stocks[0].market.bars.slice(-10);let r=screen(d,defaultPlan);assert.equal(r.rows[0].metrics.values.pb,null);assert.equal(r.rows[0].metrics.values.pe,null);assert.equal(r.rows[0].metrics.values.volatility,null);});

test('missing operator only receives explicit product default for fuzzy null threshold',()=>{const p=validateProposal({logic:'AND',window:60,conditions:[{field:'pb',op:null,value:null,quote:'估值合理'}],unsupported:[]},'估值合理');assert.equal(p.conditions[0].op,'<=');assert.equal(p.conditions[0].assumption,true);assert.throws(()=>validateProposal({logic:'AND',window:60,conditions:[{field:'pb',op:null,value:8,quote:'PB8'}],unsupported:[]},'PB8'));});
