"use client";
import { useEffect, useState } from 'react';
import {useResearch} from './workspace-context';
import { Layers3, Search, BookOpen, ShieldCheck, Sparkles, ArrowUpRight, Download, CircleHelp, Check, Clock3, ExternalLink, AlertTriangle, Activity, FileText, LoaderCircle, RotateCcw } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Checkbox } from '@/components/ui/checkbox';
import { Slider } from '@/components/ui/slider';
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table';
import dataset from '@/data/evidence.json';
import { buildDiagnosis, dimensions, growth, yi, pct, valuation, marketStats, selectDimensions } from '@/lib/engine.mjs';
type Evidence={id:string;dimension:string;type:string;stance:string;title:string;text:string;source:string;page:number;relatedSources?:string[];field:string;values:number[];formula:string;scope:string};
type AI={status:string;model:string|null;reason:string;message:string;insights:{type:string;text:string;evidenceIds:string[]}[]};
const initial=buildDiagnosis(dataset,'',dimensions,'normal');
const defaultQuestion='收入、利润与现金流的变化一致吗？';
const chips=['经营质量有哪些变化？','收入、利润与现金流的变化一致吗？','当前估值该如何理解？','与五粮液、泸州老窖相比如何？'];
const followups=['现金流增长是否代表酒类回款改善？','合同负债下降是否意味着需求走弱？','哪些结论还缺少独立证据？'];
const sources=dataset.sources;
const rawLabels:Record<string,string[]>={F01:['本期营业收入（元）','上年同期营业收入（元）'],F02:['本期归母净利润（元）','上年同期归母净利润（元）'],F03:['本期营业收入（元）','本期营业成本（元）','上年同期营业收入（元）','上年同期营业成本（元）'],F04:['本期经营现金流净额（元）','上年同期经营现金流净额（元）'],F05:['直销主营收入（万元）','批发代理主营收入（万元）'],F06:['本期末合同负债（元）','上年末合同负债（元）'],F08:['茅台营业收入（元）','五粮液营业收入（元）','泸州老窖营业收入（元）'],F09:['快照收盘价（元/股）','TTM 归母净利润（元）','最新期末股本（股）'],F10:['有效收盘样本（个）','派生年化波动率（%）']};
function Status({type}:{type:string}){return <span className={`status status-${type==='事实'?'fact':type==='推断'?'inference':'unknown'}`}>{type==='事实'?<Check size={12}/>:type==='推断'?<Sparkles size={12}/>:<CircleHelp size={12}/>} {type}</span>}
export default function Home(){
 const workspace=useResearch();
 useEffect(()=>{if(workspace?.request){setQuestion(workspace.request.question);setSelected(dimensions);setManual(false);setTab('overview');}},[workspace?.request]);
 const [question,setQuestion]=useState(defaultQuestion),[selected,setSelected]=useState<string[]>(dimensions),[manual,setManual]=useState(false),[scenario,setScenario]=useState('normal');
 const [diagnosis,setDiagnosis]=useState(initial),[ai,setAI]=useState<AI>({status:'idle',model:null,reason:'',message:'',insights:[]}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState('全部'),[tab,setTab]=useState('overview'),[focus,setFocus]=useState<Evidence|null>(null),[price,setPrice]=useState(initial.metrics.stats?.last||1258.62),[range,setRange]=useState(65),[saved,setSaved]=useState(false);
 const evidence=diagnosis.evidence as Evidence[];
 const stats=marketStats(dataset.market.bars.slice(-range));
 const visible=evidence.filter(e=>filter==='全部'||e.type===filter||e.stance===filter);
 async function diagnose(q=question,override?:string[]){
  if(!q.trim()){setError('请先输入一个研究问题。');return;}
  setBusy(true);setError('');setSaved(false);setQuestion(q);
  const dims=override||(manual?selected:selectDimensions(q));setSelected(dims);
  try{const res=await fetch('/api/diagnose',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,dimensions:dims,scenario})});const result=await res.json() as typeof initial & {ai:AI;error?:string};if(!res.ok)throw new Error(result.error||'诊断失败');setDiagnosis(result);setAI(result.ai);setFilter('全部');setTab('overview');}
  catch(e){setError(e instanceof Error?e.message:'网络请求失败；已保留上一版结果。');}
  finally{setBusy(false);}
 }
 useEffect(()=>{if(new URLSearchParams(window.location.search).get('research')==='screen'){setQuestion('筛选条件中的收入、利润与估值，是否足以证明经营改善？还缺少哪些证据？');setSelected(dimensions);setManual(false);}if(new URLSearchParams(window.location.search).get('research')==='buyback'){setQuestion('回购涉及的资金使用与股本变化，应如何结合财务资料继续核验？');setSelected(['财务趋势','估值','事件与风险'].filter(d=>dimensions.includes(d)));setManual(false);}},[]);
 useEffect(()=>{
  const ctx=(document as unknown as {modelContext?:{registerTool:(tool:unknown,opts:unknown)=>void}}).modelContext;
  if(!ctx?.registerTool)return;const lifecycle=new AbortController();
  try{ctx.registerTool({name:'open_evidence',title:'查看诊断证据',description:'在证据抽屉中打开指定ID的证据、来源和口径。',inputSchema:{type:'object',properties:{evidenceId:{type:'string'}},required:['evidenceId'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const id=(input as {evidenceId?:string})?.evidenceId;const e=(initial.allEvidence as Evidence[]).find(e=>e.id===id);if(!e)throw new Error('证据ID不存在');setFocus(e);return {id:e.id,title:e.title,source:e.source};}},{signal:lifecycle.signal});}catch{/* 不支持的浏览器仍可正常操作 */}return ()=>lifecycle.abort();
 },[]);
 function exportResearch(){const payload={company:dataset.company,dataVersion:dataset.version,dataFetchedAt:dataset.fetchedAt,exportedAt:new Date().toISOString(),diagnosis,ai,sources};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='贵州茅台_证据诊断.json';a.click();URL.revokeObjectURL(url);setSaved(true);}
 function open(id:string){const e=(diagnosis.allEvidence as Evidence[]).find(e=>e.id===id);if(e)setFocus(e);}
 const source=focus?sources.find(s=>s.id===focus.source):undefined;
 const sourceLabel=(e:Evidence)=>e.source==='MARKET'?'腾讯财经 · 行情快照':`${e.source} · 第 ${e.page} 页`;
 return <div className="shell"><aside><a className="brand" href="/">知衡<span>研究工作台</span></a><a className="nav" href="/screen"><Search size={18}/>自然语言选股</a><div className="nav active"><Layers3 size={18}/>个股诊断</div><button className="nav" onClick={()=>setTab('sources')}><BookOpen size={18}/>证据资料库</button><a className="nav" href="/events"><Clock3 size={18}/>事件情报与时间线</a><div className="aside-note"><ShieldCheck size={20}/><p>让判断有据可查</p><small>事实 · 推断 · 未知</small></div></aside><main>
 <header><span>研究工作台 / 个股诊断</span><span><FileText size={14}/> 公开证据快照版 · 2026.10.07</span></header>
 <section className="company"><div><div className="eyebrow">A 股 · 上交所 · 品牌消费 / 白酒</div><h1>贵州茅台 <span>600519.SH</span></h1><p>财务截至 2026-06-30 · 半年报未经审计 · 含财务子公司</p></div><div className="company-actions"><div className="stamp">最新财报披露<br/><strong>2026.08.15</strong></div><Button variant="outline" onClick={exportResearch}><Download size={15}/>{saved?'已导出研究记录':'导出研究记录'}</Button></div></section>
 <div className="data-notice"><Clock3 size={16}/><span>行情截至 {dataset.market.bars.at(-1)?.date}，为历史快照。当前未连接扶摇 / iFinD，公开财报与替代行情源已标明；终端动销等缺失信息不补猜。</span><button onClick={()=>setTab('sources')}>查看数据边界</button></div>
 <section className="ask"><Sparkles/><div><h2>从一个问题开始研究</h2><p>AI 解释证据与矛盾；指标由确定性引擎计算，你可以修改诊断维度。</p><form onSubmit={e=>{e.preventDefault();void diagnose();}}><Input value={question} onChange={e=>setQuestion(e.target.value)} maxLength={600} aria-label="研究问题" placeholder="例如：现金流增长是否代表经营改善？"/><Button disabled={busy||!selected.length} type="submit">{busy?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>} {busy?'分析证据中':'生成诊断'}</Button></form><div className="question-chips">{chips.map(q=><button key={q} onClick={()=>{setManual(false);void diagnose(q,selectDimensions(q));}} disabled={busy}>{q}</button>)}</div><div className="dimension-options"><span>诊断维度</span>{dimensions.map(d=><label key={d}><Checkbox checked={selected.includes(d)} onCheckedChange={v=>{setManual(true);setSelected(v?[...selected,d]:selected.filter(x=>x!==d));}}/>{d}</label>)}<button onClick={()=>{setManual(false);setSelected(dimensions);}}>恢复全维度</button></div></div></section>
 {error&&<div role="alert" className="error-box">{error} 已保留上一版证据。<button onClick={()=>void diagnose()}>重试</button></div>}
 <section className="metrics">{[['营业收入',`${yi(dataset.periods[4].revenue)} 亿`,pct(initial.metrics.revenueGrowth),'F01'],['归母净利润',`${yi(dataset.periods[4].profit)} 亿`,pct(initial.metrics.profitGrowth),'F02'],['营业收入口径毛利率',`${initial.metrics.gross.toFixed(2)}%`,'同比收窄，见计算口径','F03'],['经营现金流净额',`${yi(dataset.periods[4].cfo)} 亿`,pct(initial.metrics.cfoGrowth)+' · 含财务业务','F04']].map(([label,value,change,id])=><button key={id} onClick={()=>open(id)}><span>{label}<ArrowUpRight size={14}/></span><strong>{value}</strong><small className={change.startsWith('-')?'negative':change.startsWith('+')?'positive':''}>{change}</small><small>2026 上半年 · 点击溯源</small></button>)}</section>
 <Tabs value={tab} onValueChange={setTab}><TabsList variant="line" className="main-tabs"><TabsTrigger value="overview">证据诊断</TabsTrigger><TabsTrigger value="financial">财务期次</TabsTrigger><TabsTrigger value="market">估值与行情</TabsTrigger><TabsTrigger value="peers">同行与事件</TabsTrigger><TabsTrigger value="sources">证据资料库</TabsTrigger></TabsList>
 <TabsContent value="overview">
 <div className="analysis-heading"><div><h2>{ai.status==='idle'?'公司状态 · 证据概览':'围绕你的问题 · 诊断结果'}</h2><p>{ai.reason||'品牌消费企业需关注毛利、渠道与收入质量；财务子公司使合并现金流需要单独辨析。'}</p></div><div className="ai-state">{ai.status==='live'?<><Sparkles size={14}/>实时 AI 解读</>:ai.status==='idle'?<><ShieldCheck size={14}/>已核验资料</>:<><AlertTriangle size={14}/>AI {ai.status==='blocked'?'边界提示':'不可用'}</>}</div></div>
 {ai.message&&<div className={`ai-notice ${ai.status==='live'?'':'warning'}`} role="status">{ai.message}{ai.model&&<small>模型：{ai.model}</small>}</div>}
 {!!ai.insights.length&&<div className="ai-insights">{ai.insights.map((row,i)=><article key={i}><Status type={row.type}/><p>{row.text}</p><div>{row.evidenceIds.map(id=><button onClick={()=>open(id)} key={id}>{id} 查看依据</button>)}</div></article>)}</div>}
 <div className="filter-row"><span>证据表达</span>{['全部','事实','推断','矛盾','未知'].map(f=><button className={filter===f?'selected':''} onClick={()=>setFilter(f)} key={f}>{f}<small>{f==='全部'?evidence.length:evidence.filter(e=>e.type===f||e.stance===f).length}</small></button>)}</div>
 <div className="dimension-grid">{visible.map(e=><article className={`panel evidence-card stance-${e.stance}`} key={e.id}><div className="card-top"><span className="eyebrow">{e.dimension} / {e.id}</span><Status type={e.type}/></div><h3>{e.title}</h3><p>{e.text}</p><div className="stance"><span className={`stance-tag stance-${e.stance}`}>{e.stance}证据</span><span>{sourceLabel(e)}</span></div><button className="card-foot" onClick={()=>setFocus(e)}><BookOpen size={15}/>证据、原始字段与口径<ArrowUpRight size={15}/></button></article>)}</div>
 {!visible.length&&<div className="empty">当前维度没有此类证据。可切换筛选，或恢复全维度重新生成。</div>}
 <section className="next-research"><h2>继续验证，而不是停在结论</h2><p>追问会重新选择诊断维度，并引用对应证据。</p>{followups.map(q=><button key={q} disabled={busy} onClick={()=>{setManual(false);void diagnose(q,selectDimensions(q));}}><CircleHelp size={16}/>{q}<ArrowUpRight size={15}/></button>)}</section>
 </TabsContent>
 <TabsContent value="financial"><div className="analysis-heading"><div><h2>从期次看变化</h2><p>年度只与年度比较，半年只与上年同期比较；金额为人民币亿元。</p></div></div><div className="panel"><Table><TableHeader><TableRow>{['报告期','营业收入','归母净利润','经营现金流','归母净利 / 收入','来源'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{dataset.periods.map(p=><TableRow key={p.id}><TableCell>{p.label}</TableCell><TableCell>{yi(p.revenue)}</TableCell><TableCell>{yi(p.profit)}</TableCell><TableCell>{yi(p.cfo)}</TableCell><TableCell>{(p.profit/p.revenue*100).toFixed(2)}%</TableCell><TableCell><button className="source-link" onClick={()=>setFocus({id:p.id,dimension:'财务趋势',type:'事实',stance:'中性',title:p.label+'原始字段',text:'表中金额由原始人民币元换算为亿元；最后一列是归母净利润/营业收入，非合并净利率。',source:p.source,page:p.page,field:'营业收入 / 归母净利润 / 经营现金流 / EPS',values:[p.revenue,p.profit,p.cfo,p.eps],formula:'亿元 = 元 / 100000000；归母净利/收入 = 归母净利润 / 营业收入 × 100%',scope:'合并报表；当期累计值，未经年化'})}>{p.source} · P{p.page}</button></TableCell></TableRow>)}</TableBody></Table></div><div className="note-box"><AlertTriangle size={18}/><p>现金流含财务子公司资金往来。这里的经营现金流 / 利润不能直接用作白酒主业回款质量评分。半年报数据未经审计，年度数据见对应报告审计意见。</p></div><div className="annual-bars panel"><h3>年度收入与归母利润</h3><div className="chart-legend"><span>■ 营业收入</span><span>■ 归母净利润</span></div>{dataset.periods.slice(0,3).map(p=><div className="bar-row" key={p.id}><span>{p.label}</span><div><div style={{width:`${p.revenue/1.8e11*100}%`}}>{yi(p.revenue)}</div><div style={{width:`${p.profit/1.8e11*100}%`}}>{yi(p.profit)}</div></div></div>)}<small>数据来源：2025 年报第 6 页，单位亿元；未使用柱状高度暗示未来。</small></div></TabsContent>
 <TabsContent value="market"><div className="analysis-heading"><div><h2>估值与历史路径</h2><p>用披露利润计算，不引入盈利预测。历史行情不能推导未来涨跌。</p></div></div><div className="market-grid"><section className="panel"><div className="eyebrow">估值敏感性 · 情景计算</div><h3>价格变化，会怎样影响 PE？</h3><div className="valuation-number">{['missing','failure','stale'].includes(scenario)?'—':valuation(price,initial.metrics.ttm,dataset.periods[4].shares)?.toFixed(2)}<span>倍</span></div><p>输入价格 {price.toFixed(2)} 元 · {price===initial.metrics.stats!.last?'最新快照收盘价':'用户假设价格，非实际行情'}</p><Slider aria-label="假设股价" value={[price]} min={800} max={1800} step={1} onValueChange={v=>setPrice(v[0])}/><div className="range-label"><span>800 元</span><span>1,800 元</span></div><Button variant="outline" onClick={()=>setPrice(initial.metrics.stats!.last)}><RotateCcw size={14}/>恢复快照价格</Button><p className="formula">PE = 价格 × 期末股本 / TTM 归母净利润<br/>TTM = 2025 全年 + 2026H1 − 2025H1</p><button className="source-link" onClick={()=>open('F09')}>查看三个原始输入与计算口径</button><div className="note-box">未接入历史估值分位与一致预期，PE 本身不能证明贵或便宜。</div></section><section className="panel"><div className="chart-heading"><h3>前复权收盘价</h3><div>{[20,40,65].map(n=><button className={n===range?'selected':''} key={n} onClick={()=>setRange(n)}>{n} 日样本</button>)}</div></div>{stats&&!['missing','failure','stale'].includes(scenario)?<><PriceChart bars={dataset.market.bars.slice(-range)}/><div className="chart-stats"><div><small>区间收益</small><strong>{pct(stats.change)}</strong></div><div><small>最大收盘回撤</small><strong>{pct(stats.drawdown)}</strong></div><div><small>历史年化波动</small><strong>{stats.volatility.toFixed(2)}%</strong></div></div><p className="muted">{stats.start} 至 {stats.end} · {stats.count} 个收盘样本 · 腾讯财经</p></>:<div className="empty">行情缺失或过期，暂停当前估值和行情计算。</div>}<button className="source-link" onClick={()=>open('F10')}>查看区间、复权与计算公式</button></section></div></TabsContent>
 <TabsContent value="peers"><div className="analysis-heading"><div><h2>把公司放回行业里</h2><p>三家公司均采用 2026 上半年合并营业收入与归母净利润；样本不代表完整行业。</p></div></div><div className="panel"><Table><TableHeader><TableRow>{['公司','营业收入（亿元）','收入同比','归母净利润（亿元）','证据'].map(x=><TableHead key={x}>{x}</TableHead>)}</TableRow></TableHeader><TableBody>{[{name:'贵州茅台',code:'600519.SH',revenue:dataset.periods[4].revenue,previousRevenue:dataset.periods[3].revenue,profit:dataset.periods[4].profit,source:'H26',page:5},...dataset.peers].map(p=><TableRow key={p.code}><TableCell><strong>{p.name}</strong><small className="block muted">{p.code}</small></TableCell><TableCell>{yi(p.revenue)}</TableCell><TableCell>{pct(growth(p.revenue,p.previousRevenue))}</TableCell><TableCell>{yi(p.profit)}</TableCell><TableCell><button className="source-link" onClick={()=>setFocus({id:p.code,dimension:'行业位置',type:'事实',stance:'中性',title:p.name+'同期原始字段',text:'使用该公司半年报合并口径，金额由元换算为亿元。不同渠道、产品与财务子公司结构影响可比性。',source:p.source,page:p.page,field:'营业收入 / 上期营业收入 / 归母净利润',values:[p.revenue,p.previousRevenue,p.profit],formula:'同比 = (本期 / 上年同期 − 1) × 100%',scope:'2026 / 2025 上半年；非行业排名'})}>{p.source} · P{p.page}</button></TableCell></TableRow>)}</TableBody></Table></div><div className="note-box">收入规模和增速不等于竞争力排名。茅台持有财务子公司，现金流不与两家同行直接作质量排名。</div><div className="section-title"><h2>重要事件与待验证影响</h2><span>来自已核验财报，非完整新闻监控</span></div><div className="event-list">{['F07','F06','U01'].map(id=>{const e=(initial.allEvidence as Evidence[]).find(e=>e.id===id)!;return <article className="panel" key={id}><time>2026 上半年发生 / 08.15 披露</time><Status type={e.type}/><h3>{e.title}</h3><p>{e.text}</p><button className="source-link" onClick={()=>setFocus(e)}>查看来源与待验证边界</button></article>})}</div></TabsContent>
 <TabsContent value="sources"><div className="analysis-heading"><div><h2>原始材料与数据边界</h2><p>每个数字对应字段、单位、期次和来源。抓取时间不等于事件发生或披露时间。</p></div></div><div className="source-grid">{sources.map(s=><article className="panel" key={s.id}><div className="eyebrow">{s.id} / 一手披露材料</div><h3>{s.title}</h3><dl><dt>发布机构</dt><dd>{s.publisher}</dd><dt>报告期间</dt><dd>{s.period}</dd><dt>披露日期</dt><dd>{s.publishedAt}</dd><dt>审计状态</dt><dd>{s.audit}</dd><dt>抓取时间</dt><dd>{s.fetchedAt}</dd></dl><a className="source-link" href={s.url} target="_blank" rel="noreferrer">打开原始公告 <ExternalLink size={14}/></a><details><summary>查看原文文件 SHA-256</summary><code>{s.sha256}</code></details></article>)}</div><section className="panel data-boundary"><h3>哪些已验证，哪些仍缺失？</h3><p><strong>已验证：</strong>财报原始字段人工交叉核验；指标按公开公式计算；公开行情保留实际日期与前复权口径。</p><p><strong>替代来源：</strong>腾讯财经公开接口提供行情，未使用扶摇授权数据。非稳定官方 API，不能保证持续可用。固定快照不会自动更新。</p><p><strong>未接入：</strong>扶摇、iFinD、实时公告流、历史估值分位、市场一致预期、经销商库存和终端动销。没有独立证据时保留未知。</p><p><strong>AI 职责：</strong>围绕问题解释证据、指出矛盾及提出验证路径。模型不能修改数值；输出必须引用证据 ID，经格式与规则检查后呈现。引用存在不等于推断一定正确。</p><p><strong>资料更新：</strong>本版数据版本 {dataset.version}。页面“生成诊断”只更新分析，不代表刷新财报或行情。</p></section></TabsContent>
 </Tabs>
 <footer><div><ShieldCheck size={15}/><span>用于公司研究，不提供直接买卖建议、确定性涨跌预测或收益承诺。</span></div><div className="scenario"><span>异常演练</span><Select value={scenario} onValueChange={v=>{setScenario(v);setAI({status:'idle',model:null,reason:'',message:'',insights:[]});setDiagnosis(buildDiagnosis(dataset,question,selected,v));}}><SelectTrigger aria-label="异常演练场景"><SelectValue/></SelectTrigger><SelectContent>{[['normal','正常资料'],['missing','模拟行情缺失'],['failure','模拟接口失败'],['conflict','模拟字段冲突'],['stale','模拟行情过期']].map(([v,l])=><SelectItem key={v} value={v}>{l}</SelectItem>)}</SelectContent></Select></div></footer>
 </main><Sheet open={!!focus} onOpenChange={v=>{if(!v)setFocus(null);}}><SheetContent className="evidence-sheet"><SheetHeader><div className="eyebrow">证据验证 / {focus?.id}</div><SheetTitle>{focus?.title}</SheetTitle><SheetDescription>从结论回到原始字段，核对期次、单位与推断边界。</SheetDescription></SheetHeader>{focus&&<div className="sheet-body"><Status type={focus.type}/><p>{focus.text}</p><h3>原始字段</h3><p>{focus.field}</p>{focus.values.length>0&&<div className="raw-values">{focus.values.map((v,i)=><div key={i}><span>{rawLabels[focus.id]?.[i]||(focus.id.endsWith('.SZ')||focus.id.endsWith('.SH')?['本期营业收入（元）','上年同期营业收入（元）','本期归母净利润（元）'][i]:['营业收入（元）','归母净利润（元）','经营现金流（元）','基本 EPS（元/股）'][i])}</span><code>{v.toLocaleString('en-US',{maximumFractionDigits:2})}</code></div>)}</div>}<h3>确定性计算 / 推断路径</h3><div className="formula-box">{focus.formula}</div><h3>单位、口径与时间</h3><p>{focus.scope}</p><h3>来源与可信边界</h3>{source?<><p>{source.title} · 第 {focus.page} 页<br/>{source.publisher} · {source.audit}<br/>报告期：{source.period}<br/>披露：{source.publishedAt}<br/>抓取：{source.fetchedAt}</p><a className="source-button" href={source.url+`#page=${focus.page}`} target="_blank" rel="noreferrer">打开原文第 {focus.page} 页 <ExternalLink size={15}/></a></>:<><p>腾讯财经公开行情，前复权日线。<br/>样本：{dataset.market.bars[0].date} 至 {dataset.market.bars.at(-1)?.date}<br/>抓取：{dataset.market.fetchedAt}</p><a className="source-button" href={dataset.market.url} target="_blank" rel="noreferrer">查看行情来源 <ExternalLink size={15}/></a></>}{focus.id==='F09'&&<a className="source-link block" href={dataset.market.url} target="_blank" rel="noreferrer">收盘价来源 · 腾讯财经日线快照</a>}{focus.relatedSources?.map(id=>{const s=sources.find(x=>x.id===id);return s?<a className="source-link block" key={id} target="_blank" rel="noreferrer" href={s.url}>{id} · {s.title}</a>:null;})}<div className="note-box">{focus.type==='事实'?'事实表示来源已披露或数据已计算，不表示预测一定成立。':focus.type==='推断'?'这是一条分析推断。原始材料支持研究方向，仍需独立验证因果解释。':'当前材料不足以验证；未知不能当作零值，也不能自动当作负面事实。'}</div><Button variant="outline" onClick={()=>{setFocus(null);setManual(false);void diagnose('哪些结论还缺少独立证据？',dimensions);}}>沿证据继续追问</Button></div>}</SheetContent></Sheet></div>
}
function PriceChart({bars}:{bars:{date:string;close:number}[]}){const lo=Math.min(...bars.map(b=>b.close)),hi=Math.max(...bars.map(b=>b.close)),pad=(hi-lo)*.15||1;const points=bars.map((b,i)=>`${45+i/(bars.length-1)*510},${190-(b.close-lo+pad)/(hi-lo+2*pad)*165}`).join(' ');return <svg viewBox="0 0 580 230" className="price-chart" role="img" aria-label={`前复权收盘价，${bars[0].date}至${bars.at(-1)?.date}`}><defs><linearGradient id="pricefill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#2555db" stopOpacity=".15"/><stop offset="1" stopColor="#2555db" stopOpacity="0"/></linearGradient></defs>{[lo,(hi+lo)/2,hi].map(v=>{const y=190-(v-lo+pad)/(hi-lo+2*pad)*165;return <g key={v}><line x1="45" x2="560" y1={y} y2={y} stroke="#e6edf5" strokeDasharray="4 4"/><text x="0" y={y+4} fill="#7e8ca0" fontSize="12">{v.toFixed(0)}</text></g>})}<polygon points={`45,195 ${points} 555,195`} fill="url(#pricefill)"/><polyline points={points} fill="none" stroke="#2555db" strokeWidth="2.5"/><text x="45" y="222" fill="#7e8ca0" fontSize="12">{bars[0].date}</text><text x="475" y="222" fill="#7e8ca0" fontSize="12">{bars.at(-1)?.date}</text></svg>}
