'use client';
import {useEffect,useState,useRef} from 'react';
import {useResearch} from './workspace-context';import {Layers3,Sparkles,Play,Plus,X,Check,AlertTriangle,Bookmark,FileText,SlidersHorizontal,GitCompareArrows,LoaderCircle,Download,Search,ShieldCheck} from 'lucide-react';
import baseline from '@/data/screen.json';import {metricDefs,defaultPlan,conflicts,relaxations,changes} from '@/lib/screen.mjs';import '@/app/screen/screen.css';
type Field=keyof typeof metricDefs;type Condition={id:string;field:Field;op:string;value:number;assumption?:boolean;quote?:string};type Plan={logic:string;window:number;conditions:Condition[];unsupported:string[];omitted?:string[]};
type CheckRow=Condition&{label:string;unit:string;actual:number|null;status:string;reason:string;source:string;scope:string;formula:string;rawInputs:Record<string,number|null>;pages:Record<string,number>;price:number|null};
type Row={code:string;name:string;status:string;checks:CheckRow[];metrics:{values:Record<string,number|null>;window:{start:string;end:string;prices:number;returns:number}|null};raw:Record<string,number|null>;note:string;market:typeof baseline.stocks[0]['market'];source:string;financialAsOf:string};
type Run={dataVersion:string;asOf:string;scenario:string;universe:string;plan:Plan;rows:Row[];sources:typeof baseline.sources;counts:{included:number;excluded:number;unknown:number};generatedAt:string};type Saved={id:string;createdAt:string;intent:string;plan:Plan;run:Run};
const statusOrder:Record<string,number>={included:0,unknown:1,excluded:2};
const labels:Record<string,string>={included:'入选',excluded:'排除',unknown:'无法判定',pass:'满足',fail:'不满足'};
const rawLabels:Record<string,string>={revenue:'营业收入（元）',previousRevenue:'上年同期营业收入（元）',profit:'归母净利润（元）',previousProfit:'上年同期归母净利润（元）',equity:'归母净资产（元）',shares:'期末总股本（股）',annualProfit:'2025全年归母净利润（元）',ttmProfit:'TTM归母净利润（元）',cfo:'经营现金流净额（元）'};
const examples=['经营改善、估值合理、走势相对稳定','收入同比大于0%，市净率小于8倍，近60交易日年化波动率低于30%','收入同比大于10%，收入同比小于0%','市盈率小于25倍，经营现金流大于0亿元'];
const fmt=(v:number|null|undefined,d=2)=>v==null?'缺失':v.toLocaleString('zh-CN',{maximumFractionDigits:d,minimumFractionDigits:d});
export default function Screen(){
 const workspace=useResearch();const [data,setData]=useState(baseline),[provider,setProvider]=useState('');
 const [stage,setStage]=useState('idea');const stageTop=useRef<HTMLDivElement>(null);
 useEffect(()=>{stageTop.current?.scrollIntoView({block:'start'});},[stage]);
 const [intent,setIntent]=useState(examples[0]),[plan,setPlan]=useState<Plan>(structuredClone(defaultPlan) as Plan),[confirmed,setConfirmed]=useState(false),[run,setRun]=useState<Run|null>(null),[previous,setPrevious]=useState<Run|null>(null),[busy,setBusy]=useState(''),[error,setError]=useState(''),[message,setMessage]=useState(''),[model,setModel]=useState(''),[scenario,setScenario]=useState('normal'),[tab,setTab]=useState('全部'),[selected,setSelected]=useState<string[]>([]),[compare,setCompare]=useState(false),[focus,setFocus]=useState<{row:Row;check:CheckRow}|null>(null),[saved,setSaved]=useState<Saved[]>([]),[savedOpen,setSavedOpen]=useState(false),[sourceOpen,setSourceOpen]=useState(false),[executedFingerprint,setExecutedFingerprint]=useState(''),[executedIntent,setExecutedIntent]=useState('');
 const fingerprint=JSON.stringify({plan,scenario,intent}),dirty=!!run&&fingerprint!==executedFingerprint,issues=conflicts(plan);
 const simulations:Record<string,string>={normal:'真实快照',missing:'模拟：五粮液利润缺失',failure:'模拟：数据接口失败',stale:'模拟：行情过期',conflict:'模拟：茅台收入冲突'};
 async function json(r:Response){if(!r.headers.get('content-type')?.includes('application/json'))throw Error('服务暂时不可用，草稿与上一版结果已保留。');return r.json();}
 async function loadSaved(){try{const r=await fetch('/api/screen/saved');const x=await json(r) as {items:Saved[];error?:string};if(!r.ok)throw Error(x.error);setSaved(x.items);}catch(e){setError(e instanceof Error?e.message:'读取失败');}}
 useEffect(()=>{loadSaved();},[]);
 function edit(p:Plan){setStage('conditions');setPlan(p);setConfirmed(false);setMessage('条件已修改，请检查并确认后执行。');setError('');}
 async function parse(){setBusy('parse');setError('');setModel('');try{const r=await fetch('/api/screen/parse',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text:intent})});const x=await json(r) as {plan:Plan;model:string;message:string;error?:string};if(!r.ok)throw Error(x.error);setStage('conditions');setPlan(x.plan);setModel(x.model);setMessage(x.message);setConfirmed(false);}catch(e){setError(e instanceof Error?e.message:'意图解析失败');}finally{setBusy('');}}
 async function execute(){setBusy('run');setError('');try{const r=await fetch('/api/screen/run',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan,scenario,confirmed})});const x=await json(r) as Run&{error?:string;researchData?:typeof baseline;provider?:{status:string}};if(!r.ok)throw Error(x.error);workspace?.updateScreen({intent,counts:x.counts,conditions:plan.conditions.length,rules:plan.conditions.map(c=>`${metricDefs[c.field].label} ${c.op} ${c.value}${metricDefs[c.field].unit}`).join('；')});if(x.researchData)setData(x.researchData);setProvider(x.provider?.status||'');setStage('results');setPrevious(run);setRun(x);setExecutedFingerprint(fingerprint);setExecutedIntent(intent);setTab('全部');setSelected([]);setCompare(false);setMessage('筛选完成。入选仅表示满足当前数据条件，不构成投资建议。');}catch(e){setError(e instanceof Error?e.message:'筛选失败');}finally{setBusy('');}}
 async function save(){if(!run||dirty)return;setBusy('save');setError('');try{const r=await fetch('/api/screen/saved',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({intent,plan:run.plan,scenario:run.scenario,confirmed:true})});const x=await json(r) as Saved&{error?:string};if(!r.ok)throw Error(x.error);setSaved([x,...saved]);setMessage('策略与结果快照已保存，刷新后可恢复。');}catch(e){setError(e instanceof Error?e.message:'保存失败，可先导出');}finally{setBusy('');}}
 function restore(s:Saved){setStage('results');workspace?.updateScreen({intent:s.intent,counts:s.run.counts,conditions:s.plan.conditions.length,rules:s.plan.conditions.map(c=>`${metricDefs[c.field].label} ${c.op} ${c.value}${metricDefs[c.field].unit}`).join('；')});setIntent(s.intent);setExecutedIntent(s.intent);setPlan(s.plan);setScenario(s.run.scenario);setRun(s.run);setData({...baseline,version:s.run.dataVersion,asOf:s.run.asOf,stocks:s.run.rows.map(r=>({...baseline.stocks.find(b=>b.code===r.code)!,raw:r.raw,market:r.market}))} as typeof baseline);setProvider(s.run.dataVersion.endsWith('-fuyao')?'connected':'');setPrevious(null);setConfirmed(false);setExecutedFingerprint(JSON.stringify({plan:s.plan,scenario:s.run.scenario,intent:s.intent}));setSavedOpen(false);setMessage('已载入保存时的结果快照；数据版本与时点沿用该记录，重新执行才使用现有数据。');setSelected([]);setCompare(false);}
 function download(){if(!run)return;const blob=new Blob([JSON.stringify({intent:executedIntent,run,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='知衡-选股条件与证据.json';a.click();URL.revokeObjectURL(url);}
 const rows=run?[...run.rows].filter(r=>tab==='全部'||labels[r.status]===tab).sort((a,b)=>statusOrder[a.status]-statusOrder[b.status]||a.code.localeCompare(b.code)):[];const delta=run&&previous?changes(previous,run):[];
 const sensitivity=run&&!dirty?relaxations(data,run.plan,run.scenario):[];
 return <div className="screen-app"><header className="screen-header"><button onClick={()=>setSavedOpen(true)}><Bookmark size={16}/> 已存策略 {saved.length}</button></header>
 <main className="screen-main"><div ref={stageTop} className="selection-flow"><nav aria-label="选股流程">{[['idea','1','描述想法'],['conditions','2','检查条件'],['results','3','查看结果']].map(([id,num,label])=><button key={id} aria-current={stage===id?'step':undefined} disabled={id==='results'&&!run} onClick={()=>setStage(id)}><span>{num}</span>{label}</button>)}</nav><button className="screen-link" onClick={()=>setSourceOpen(true)}><FileText size={14}/>数据来源</button></div>
 <div className="screen-scope"><span>范围：茅台、五粮液、泸州老窖</span><span>财务 2026H1 · 行情 2026-09-30 · {provider==='connected'?'扶摇已核验':provider==='not_configured'?'扶摇未配置 · 公开快照':provider==='simulation'?'隔离异常演练':'执行时核验扶摇'}</span></div>
 <div className="screen-workbench"><section hidden={stage!=='idea'} className="screen-panel screen-intent"><div className="intent-heading"><h1>用一句话，描述选股想法</h1><p>AI 整理成条件，由你检查后执行。</p></div><textarea aria-label="你希望检查什么样的公司？" id="screen-intent" value={intent} maxLength={1200} onChange={e=>{setIntent(e.target.value);setConfirmed(false);setMessage('意图文字已修改，下方仍是上一份条件草稿。请重新解析或手动修改后再确认执行。');}}/><div className="screen-examples">{examples.slice(0,2).map((q,i)=><button key={q} onClick={()=>{setIntent(q);setConfirmed(false);setMessage('已填入示例意图，请点击AI解析。');}}>{['经营改善、估值合理','收入增长、低波动'][i]}</button>)}</div><button className="screen-primary" disabled={!!busy} onClick={parse}>{busy==='parse'?<LoaderCircle className="screen-spin" size={17}/>:<Sparkles size={17}/>} {busy==='parse'?'解析意图中…':'AI 解析为条件'}</button><p className="screen-meta">文本由 OpenRouter 处理；AI 不生成财务数字。</p><button className="manual-entry" onClick={()=>{edit(structuredClone(defaultPlan) as Plan);setModel('');setMessage('已载入示例条件，请检查阈值。');}}>直接编辑示例条件</button></section>
 <section hidden={stage!=='conditions'} className="screen-panel screen-builder"><div className="stage-caption"><span>检查指标和阈值，所有条件须同时满足。</span><button onClick={()=>setStage('idea')}>修改想法</button></div><div className="screen-step"><span>02</span><h2>筛选条件</h2></div><div className="screen-builder-meta"><label>行情窗口 <select aria-label="行情窗口" value={plan.window} onChange={e=>edit({...plan,window:Number(e.target.value)})}>{[20,30,60,64].map(n=><option key={n} value={n}>{n} 个交易日</option>)}{![20,30,60,64].includes(plan.window)&&<option value={plan.window}>{plan.window} 个交易日</option>}</select></label><span>{model?`实时模型 · ${model}`:'手动 / 示例草稿'}</span></div>
 <div className="condition-list">{plan.conditions.map((c,i)=><div key={c.id} className="condition-item"><div className="condition-controls"><span>{i===0?'IF':'AND'}</span><select aria-label={`条件${i+1}指标`} value={c.field} onChange={e=>{const f=e.target.value as Field;edit({...plan,conditions:plan.conditions.map(x=>x.id===c.id?{...x,field:f,op:metricDefs[f].op,value:metricDefs[f].preset,assumption:true,quote:undefined}:x)});}}>{Object.entries(metricDefs).map(([k,v])=><option value={k} key={k}>{v.label}</option>)}</select><select aria-label={`条件${i+1}运算符`} value={c.op} onChange={e=>edit({...plan,conditions:plan.conditions.map(x=>x.id===c.id?{...x,op:e.target.value}:x)})}>{['>=','>','<=','<','='].map(op=><option value={op} key={op}>{op}</option>)}</select><input aria-label={`条件${i+1}阈值`} type="number" step="any" value={Number.isFinite(c.value)?c.value:''} onChange={e=>edit({...plan,conditions:plan.conditions.map(x=>x.id===c.id?{...x,value:e.target.value===''?NaN:Number(e.target.value),assumption:false}:x)})}/><small>{metricDefs[c.field].unit}</small><button aria-label={`删除条件${i+1}`} onClick={()=>edit({...plan,conditions:plan.conditions.filter(x=>x.id!==c.id)})}><X size={15}/></button></div><div className="condition-origin"><span className={c.assumption?'assumption':'explicit'}>{c.assumption?'示例阈值 · 需确认':'明确阈值'}</span><span>{c.quote?`对应意图：${c.quote}`:'用户手动添加'}</span></div></div>)}</div>
 <button className="screen-add" onClick={()=>edit({...plan,conditions:[...plan.conditions,{id:crypto.randomUUID(),field:'cfo',op:'>=',value:0,assumption:true}]})} disabled={plan.conditions.length>=12}><Plus size={15}/> 添加条件</button>
 {plan.unsupported.map((q,i)=><div className="screen-unsupported" key={i}><b>尚未支持：{q}</b><p>当前不能完整执行这部分意图。请改写或明确移除此项，不能静默忽略。</p><button onClick={()=>edit({...plan,unsupported:plan.unsupported.filter((_,j)=>i!==j),omitted:[...(plan.omitted||[]),q]})}>明确移除此项，仅检查其余条件</button></div>)}{plan.omitted?.length&&<p className="screen-meta">已明确移除：{plan.omitted.join('；')}</p>}
 {issues.length>0&&<div className="screen-warning" role="alert"><AlertTriangle size={17}/><div>{issues.join('；')}。修改后才能执行；不会自动放宽。</div></div>}
 <label className="screen-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/> 我已检查指标、阈值、AND 关系及样本范围，按当前条件执行</label><button className="screen-primary" disabled={!!busy||!confirmed||!!issues.length||!!plan.unsupported.length||!plan.conditions.length||plan.conditions.some(c=>!Number.isFinite(c.value))} onClick={execute}>{busy==='run'?<LoaderCircle size={17} className="screen-spin"/>:<Play size={16}/>} 确认条件并执行筛选</button></section></div>
 {error&&<div role="alert" className="screen-error">{error}</div>}{message&&stage!=='idea'&&<div role="status" className="screen-message">{message}</div>}
 <section hidden={stage!=='results'} className="screen-panel screen-results"><div className="screen-results-title"><div className="screen-step"><span>03</span><h2>筛选结果</h2></div><div className="screen-result-actions"><button onClick={()=>setStage('conditions')}>修改条件</button><details className="data-simulation"><summary>异常演练</summary><label>数据状态<select aria-label="数据状态" value={scenario} onChange={e=>{setScenario(e.target.value);setConfirmed(false);}}>{Object.entries(simulations).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></details><button disabled={!run||dirty||!!busy} onClick={save}><Bookmark size={15}/> 保存策略与结果</button><button disabled={!run} onClick={download}><Download size={15}/> 导出</button></div></div>
 {dirty&&<div className="screen-warning"><AlertTriangle size={17}/> 条件、意图或数据状态已改变。下方保留的是上一次结果，确认重算后才更新；暂不能保存为新策略。</div>}
 {!run?<div className="screen-empty"><Search size={28}/><h3>先检查条件，再查看候选</h3><p>系统不会为了返回股票而自动放宽条件。数据不足会明确显示。</p></div>:<><div className="screen-run-info"><span>执行 {new Date(run.generatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})} CST</span><span>{run.dataVersion} · {run.plan.window} 交易日</span><b>{simulations[run.scenario]} · 点击指标查看证据</b></div><div className="screen-result-tabs">{['全部','入选','排除','无法判定'].map(t=><button key={t} className={tab===t?'screen-selected':''} onClick={()=>setTab(t)}>{t}<b>{t==='全部'?run.rows.length:t==='入选'?run.counts.included:t==='排除'?run.counts.excluded:run.counts.unknown}</b></button>)}<button className="screen-compare-button" disabled={selected.length<2} onClick={()=>setCompare(true)}><GitCompareArrows size={15}/> 比较所选 ({selected.length})</button></div>
 {previous&&<div className="screen-delta"><b>与上次执行相比</b>{delta.length?delta.map((d:{code:string;name:string;before:string;after:string})=><span key={d.code}>{d.name}：{labels[d.before]} → {labels[d.after]}</span>):<span>候选归属未变化；数值与每项依据见下方。</span>}</div>}
 <div className="screen-stock-list">{rows.length===0&&<div className="screen-empty"><p>当前分类没有股票。可以查看其他分类，或检查条件与缺失数据。</p></div>}{rows.map(row=><article key={row.code} className="screen-stock"><div className="screen-stock-heading"><div><input aria-label={`比较${row.name}`} type="checkbox" checked={selected.includes(row.code)} onChange={e=>setSelected(e.target.checked?[...selected,row.code]:selected.filter(x=>x!==row.code))}/><h3>{row.name}</h3><small>{row.code}</small><span className={`screen-status ${row.status}`}>{labels[row.status]}</span></div>{row.code==='600519.SH'?<div className="screen-stock-links"><a href="/?research=screen">研究这家公司</a></div>:<small className="screen-meta">完整研究仅覆盖茅台</small>}</div><p className="screen-reason">{row.status==='included'?'所有已确认条件均满足；筛选通过不代表公司全面改善。':row.status==='unknown'?'必要数据缺失，暂不能确认入选。':'存在不满足的条件；缺失项保留为未知。'}</p><div className="screen-checks">{row.checks.map(c=><button key={c.id} className={`screen-check ${c.status}`} onClick={()=>setFocus({row,check:c})}><div><span>{c.status==='pass'?<Check size={14}/>:<AlertTriangle size={14}/>} {c.label}</span><b>{fmt(c.actual)} <small>{c.unit}</small></b></div><span>条件 {c.op} {c.value} {c.unit} · {c.status==='unknown'?'无法判定':labels[c.status]}</span>{c.status==='unknown'&&<small>{c.reason}</small>}<em>检查原始字段与计算口径</em></button>)}</div><details className="screen-stock-note"><summary>公司分析边界</summary><p>{row.note}</p></details></article>)}</div>
 <details className="screen-sensitivity"><summary><SlidersHorizontal size={17}/> 条件变化会怎样影响结果？</summary><p>在同一历史快照上每次只放宽一条条件，其余条件保持不变。这是条件敏感性重算，不是未来表现预测。</p>{dirty?<p className="screen-meta">请先执行当前草稿，再比较它的条件影响。</p>:<div className="sensitivity-grid">{sensitivity.map((x:{id:string;label:string;from:number;to:number;op:string;result:Run})=><article key={x.id}><b>{x.label}</b><span>{x.op} {x.from} → {x.op} {x.to}</span><strong>入选 {run.counts.included} → {x.result.counts.included}</strong><p>{changes(run,x.result).map((d:{name:string;before:string;after:string})=>`${d.name}：${labels[d.before]}→${labels[d.after]}`).join('；')||'归属未变化，其他条件仍形成约束。'}</p><button onClick={()=>edit({...plan,conditions:plan.conditions.map(c=>c.id===x.id?{...c,value:x.to,assumption:false}:c)})}>应用到草稿</button></article>)}</div>}</details></>}
 </section><footer className="screen-footer"><details><summary>数据与使用边界</summary><p>用于条件研究，不提供买卖建议。按筛选状态分组，同组按代码展示，不是投资排名。暂未接入扶摇/iFinD，无全市场筛选、回测或后台监控；可比较与保存真实快照。</p></details></footer>
 </main>
 {focus&&<div className="screen-overlay" onClick={()=>setFocus(null)}><aside className="screen-drawer" role="dialog" aria-modal="true" aria-label="筛选证据" onClick={e=>e.stopPropagation()}><div className="screen-modal-title"><b>{focus.row.name} · {focus.check.label}</b><button aria-label="关闭筛选证据" onClick={()=>setFocus(null)}><X size={20}/></button></div><span className={`screen-status ${focus.check.status}`}>客观数据 · {focus.check.status==='unknown'?'无法判定':labels[focus.check.status]}</span><h2>{fmt(focus.check.actual)} {focus.check.unit}</h2><p>检查条件：{focus.check.op} {focus.check.value} {focus.check.unit}</p><h3>统计口径与时间</h3><p>{focus.check.scope}</p><p>财务期末 {focus.row.financialAsOf}<br/>行情时点 {focus.row.market.asOf}<br/>行情抓取 {focus.row.market.fetchedAt}</p><h3>原始字段</h3>{Object.entries(focus.check.rawInputs).map(([k,v])=><div className="screen-raw" key={k}><small>{rawLabels[k]||k}</small><b>{fmt(v)}</b>{v!==null&&<a href={(run?.sources||data.sources).find(s=>s.id===(k==='annualProfit'?'A25':focus.row.source))?.url+`#page=${focus.check.pages[k]|| (k==='annualProfit'?6:1)}`} target="_blank" rel="noopener noreferrer">原文第 {focus.check.pages[k]||(k==='annualProfit'?6:1)} 页</a>}</div>)}{focus.check.price!==null&&<div className="screen-raw"><small>未复权收盘价（元/股）</small><b>{fmt(focus.check.price)}</b><a target="_blank" rel="noopener noreferrer" href={focus.row.market.rawUrl}>行情原始接口</a></div>}{['volatility','drawdown'].includes(focus.check.field)&&<><p>样本：{focus.row.metrics.window?.start} 至 {focus.row.metrics.window?.end}，{focus.row.metrics.window?.prices} 个收盘价 / {focus.row.metrics.window?.returns} 个日收益率。前复权由供应商计算，复权算法未独立审计。</p><details><summary>查看完整计算样本</summary><pre>{JSON.stringify(focus.row.market.bars.slice(-(run!.plan.window+1)),null,2)}</pre></details></>}<h3>确定性计算</h3><code className="screen-formula">{focus.check.formula}</code>{focus.check.status==='unknown'&&<div className="screen-warning">{focus.check.reason}</div>}<h3>数据来源</h3><p>{data.sources.find(s=>s.id===focus.row.source)?.title}<br/>披露 {data.sources.find(s=>s.id===focus.row.source)?.publishedAt} · 未经审计<br/>采集 {data.sources.find(s=>s.id===focus.row.source)?.fetchedAt}</p><a className="screen-original" href={data.sources.find(s=>s.id===focus.row.source)?.url} target="_blank" rel="noopener noreferrer">查看财报原文</a>{focus.check.field==='pe'&&<a className="screen-original" href={data.sources.find(s=>s.id==='A25')?.url+'#page=6'} target="_blank" rel="noopener noreferrer">TTM全年利润来源 · 茅台2025年报第6页</a>}<p className="screen-meta">财报 SHA-256：{data.sources.find(s=>s.id===focus.row.source)?.sha256}<br/>行情 SHA-256：{focus.row.market.sha256}</p><div className="screen-warning">解释边界：{focus.row.note}</div></aside></div>}
 {compare&&run&&<div className="screen-overlay" onClick={()=>setCompare(false)}><section className="screen-compare-modal" role="dialog" aria-modal="true" aria-label="候选股票比较" onClick={e=>e.stopPropagation()}><div className="screen-modal-title"><h2>相同口径比较</h2><button aria-label="关闭比较" onClick={()=>setCompare(false)}><X/></button></div><p className="screen-meta">2026上半年财务与2026-09-30行情。差异描述事实，不产生优劣排名。</p><div className="screen-table-scroll"><table><thead><tr><th>指标</th>{run.rows.filter(r=>selected.includes(r.code)).map(r=><th key={r.code}>{r.name}<small>{labels[r.status]}</small></th>)}</tr></thead><tbody>{Object.entries(metricDefs).map(([f,d])=><tr key={f}><th>{d.label}（{d.unit}）</th>{run.rows.filter(r=>selected.includes(r.code)).map(r=><td key={r.code}>{fmt(r.metrics.values[f])}</td>)}</tr>)}</tbody></table></div><p className="screen-meta">缺失PE保留缺失，不以半年利润直接年化。现金流与利润方向可能不同，继续查看原始凭据。</p></section></div>}
 {savedOpen&&<div className="screen-overlay" onClick={()=>setSavedOpen(false)}><aside className="screen-drawer" role="dialog" aria-modal="true" aria-label="已保存策略" onClick={e=>e.stopPropagation()}><div className="screen-modal-title"><h2>已保存的研究策略</h2><button aria-label="关闭已保存策略" onClick={()=>setSavedOpen(false)}><X/></button></div><p>每份记录保存意图、条件、数据版本和结果凭据，刷新可恢复；仅本浏览器工作区可见，无跨设备同步。</p>{saved.length===0&&<p className="screen-meta">执行一次筛选后即可保存。</p>}{saved.map(s=><article className="screen-save-item" key={s.id}><b>{s.intent}</b><small>{new Date(s.createdAt).toLocaleString('zh-CN')} · {s.run.dataVersion}</small><p>入选 {s.run.counts.included} · 排除 {s.run.counts.excluded} · 无法判定 {s.run.counts.unknown}</p><button onClick={()=>restore(s)}>载入这一版</button></article>)}</aside></div>}
 {sourceOpen&&<div className="screen-overlay" onClick={()=>setSourceOpen(false)}><aside className="screen-drawer" role="dialog" aria-modal="true" aria-label="选股数据边界" onClick={e=>e.stopPropagation()}><div className="screen-modal-title"><h2>数据口径与已知边界</h2><button aria-label="关闭数据边界" onClick={()=>setSourceOpen(false)}><X/></button></div><p>{data.universe}。不是行业完整成分，不做市场排名。财务为最新收录半年报，未经审计，期间为2026-01-01至2026-06-30。</p><p>行情截止{data.asOf}，{provider==='connected'?'扶摇历史日线（服务端缓存15分钟）':'初始公开日线快照，执行时优先核验扶摇'}。估值用未复权最后收盘价，走势用前复权路径。股本为半年末近似，不含之后可能发生的变动。仅历史研究，不以日历天判断节假日期间行情缺失。</p><p>“经营改善”只是用户选择的收入/利润条件；不等价于主业质量全面改善。PB受净资产口径影响，≤8只是可修改示例，不能据此称公司便宜。五粮液和老窖未收录2025全年利润，PE-TTM保留缺失。</p>{data.sources.map(s=><article className="screen-source" key={s.id}><a href={s.url} target="_blank" rel="noopener noreferrer">{s.id} · {s.title}</a><p>披露{s.publishedAt} · {s.audit}<br/>采集{s.fetchedAt}</p><small>SHA-256 {s.sha256}</small></article>)}<p>模型经OpenRouter提取意图；确定性引擎执行条件并计算所有数字；金融数据层保存核验字段与来源。已接入扶摇行情及财务核验；未配置密钥时明确使用公开历史快照，权限/冲突/失败时阻止执行。iFinD未连接；无后台自动刷新，不执行回测或监控。</p></aside></div>}
 </div>;
}
