import {growth,marketStats} from './engine.mjs';
export const metricDefs={revenueGrowth:{label:'营业收入同比',unit:'%',preset:0,op:'>=',scope:'2026上半年合并营业收入对比2025同期，不含利息收入',formula:'(本期收入 / 上年同期收入 − 1) × 100%',inputs:['revenue','previousRevenue']},profitGrowth:{label:'归母净利润同比',unit:'%',preset:0,op:'>=',scope:'2026上半年归母净利润对比2025同期，非环比',formula:'(本期归母利润 / 上年同期归母利润 − 1) × 100%',inputs:['profit','previousProfit']},pb:{label:'市净率 PB',unit:'倍',preset:8,op:'<=',scope:'2026-09-30未复权收盘价 × 2026半年末股本 / 归母净资产；期末股本近似',formula:'收盘价 × 期末股本 / 归母净资产',inputs:['equity','shares']},pe:{label:'市盈率 PE-TTM',unit:'倍',preset:25,op:'<=',scope:'2026-09-30收盘价 × 半年末股本 / TTM归母利润；五粮液和老窖缺全年利润',formula:'收盘价 × 期末股本 / (2025全年利润 + 2026H1 − 2025H1)',inputs:['annualProfit','profit','previousProfit','shares']},volatility:{label:'年化波动率',unit:'%',preset:35,op:'<=',scope:'前复权日线；最近N个交易日对数收益样本标准差，年化252',formula:'stdev(log(当日收盘/前日收盘)) × √252 × 100%',inputs:[]},drawdown:{label:'最大收盘回撤幅度',unit:'%',preset:15,op:'<=',scope:'前复权收盘路径；显示正值幅度，不是盘中回撤',formula:'max(1 − 当日收盘 / 此前最高收盘) × 100%',inputs:[]},cfo:{label:'经营现金流净额',unit:'亿元',preset:0,op:'>=',scope:'2026上半年合并现金流；含财务业务时不能直接当主业回款',formula:'合并经营现金流净额（元）/ 100000000',inputs:['cfo']}};
export const defaultPlan={logic:'AND',window:60,conditions:['revenueGrowth','profitGrowth','pb','volatility'].map((field,i)=>({id:'c'+i,field,op:metricDefs[field].op,value:metricDefs[field].preset,assumption:true,quote:['经营改善','经营改善','估值合理','走势相对稳定'][i]})),unsupported:[]};
export function advice(text){return /买入|卖出|荐股|抄底|建仓|清仓|稳赚|必涨|目标价|保证.*收益|翻倍|buy\b|sell\b/i.test(text);}
export function validatePlan(plan){if(!plan||plan.logic!=='AND'||!Number.isInteger(plan.window)||plan.window<10||plan.window>64||!Array.isArray(plan.conditions)||!plan.conditions.length||plan.conditions.length>12)throw new Error('条件结构无效：仅支持AND、10–64交易日和1–12条条件');
 const ids=new Set();for(const c of plan.conditions){if(!c||!metricDefs[c.field]||!(['>=','<=','>','<','='].includes(c.op)||(c.value===null&&c.op===null))||!Number.isFinite(c.value)||Math.abs(c.value)>100000||typeof c.id!=='string'||ids.has(c.id))throw new Error('条件字段、运算符或数值无效');ids.add(c.id);}
 if(!Array.isArray(plan.unsupported)||plan.unsupported.length)throw new Error('存在尚未支持的意图，请先澄清或明确移除');return plan;
}
export function conflicts(plan){const issues=[];for(const field of Object.keys(metricDefs)){const cs=plan.conditions.filter(c=>c.field===field);let low=-Infinity,high=Infinity,strictLow=false,strictHigh=false;for(const c of cs){if(['>=','>','='].includes(c.op)&&(c.value>low||c.value===low&&c.op==='>')){low=c.value;strictLow=c.op==='>';}if(['<=','<','='].includes(c.op)&&(c.value<high||c.value===high&&c.op==='<')){high=c.value;strictHigh=c.op==='<';}}
 if(low>high||low===high&&(strictLow||strictHigh))issues.push(`${metricDefs[field].label}上下限互相矛盾`);
 if(['pb','pe','volatility','drawdown'].includes(field)&&high<0)issues.push(`${metricDefs[field].label}不能要求负数上限`);
 }return issues;}
const compare=(v,op,t)=>op==='>='?v>=t:op==='<='?v<=t:op==='>'?v>t:op==='<'?v<t:v===t;
export function stockMetrics(stock,window,scenario='normal'){
 const stats=marketStats(stock.market.bars.slice(-(window+1)));const aligned=stats&&stats.count===window+1&&stats.end===stock.market.asOf;
 const price=stock.market.rawClose,r=stock.raw;
 const vals={revenueGrowth:growth(r.revenue,r.previousRevenue),profitGrowth:growth(r.profit,r.previousProfit),pb:r.equity>0&&r.shares>0&&price>0?price*r.shares/r.equity:null,pe:r.ttmProfit>0&&r.shares>0&&price>0?price*r.shares/r.ttmProfit:null,volatility:aligned?stats.volatility:null,drawdown:aligned?-stats.drawdown:null,cfo:Number.isFinite(r.cfo)?r.cfo/1e8:null};
 const reasons={pe:vals.pe===null?'缺少正的TTM归母利润，未用半年利润直接年化替代':null};
 if(scenario==='missing'&&stock.code==='000858.SZ'){vals.profitGrowth=null;reasons.profitGrowth='异常演练：归母利润上期值缺失';}
 if(scenario==='conflict'&&stock.code==='600519.SH'){vals.revenueGrowth=null;reasons.revenueGrowth='异常演练：收入字段冲突，停止合并';}
 for(const field of Object.keys(vals)){if(scenario==='failure'||scenario==='stale'&&['pb','pe','volatility','drawdown'].includes(field)){vals[field]=null;reasons[field]=scenario==='failure'?'异常演练：数据接口失败':'异常演练：行情过期，停止当前筛选判断';}if(!Number.isFinite(vals[field])){vals[field]=null;reasons[field]??='必要字段缺失或不足指定窗口';}}
 return {values:vals,reasons,window:aligned?{start:stats.start,end:stats.end,prices:stats.count,returns:stats.count-1}:null};
}
export function screen(data,plan,scenario='normal'){
 validatePlan(plan);if(!['normal','missing','failure','stale','conflict'].includes(scenario))throw new Error('异常场景无效');const issues=conflicts(plan);if(issues.length)throw new Error(issues.join('；'));
 const rows=data.stocks.map(stock=>{const m=stockMetrics(stock,plan.window,scenario);const checks=plan.conditions.map(c=>{const value=m.values[c.field];const status=value===null?'unknown':compare(value,c.op,c.value)?'pass':'fail';return {...c,label:metricDefs[c.field].label,unit:metricDefs[c.field].unit,actual:value,status,reason:status==='unknown'?m.reasons[c.field]:`实际 ${value.toFixed(2)} ${metricDefs[c.field].unit} ${status==='pass'?'符合':'不符合'} ${c.op} ${c.value}`,source:stock.source,scope:metricDefs[c.field].scope,formula:metricDefs[c.field].formula,rawInputs:Object.fromEntries(metricDefs[c.field].inputs.map(k=>[k,stock.raw[k]??null])),pages:stock.pages,price:['pb','pe'].includes(c.field)?stock.market.rawClose:null};});
 // A known failure proves exclusion even if other fields are missing. Missing checks remain visible.
 const status=checks.some(c=>c.status==='fail')?'excluded':checks.some(c=>c.status==='unknown')?'unknown':'included';return {code:stock.code,name:stock.name,status,checks,metrics:m,raw:stock.raw,note:stock.note,market:stock.market,source:stock.source,financialAsOf:stock.financialAsOf};});
 return {dataVersion:data.version,asOf:data.asOf,scenario,universe:data.universe,plan,rows,sources:data.sources,counts:{included:rows.filter(r=>r.status==='included').length,excluded:rows.filter(r=>r.status==='excluded').length,unknown:rows.filter(r=>r.status==='unknown').length},generatedAt:new Date().toISOString()};
}
export function changes(before,after){return after.rows.flatMap(r=>{const old=before?.rows.find(x=>x.code===r.code);return old&&old.status!==r.status?[{code:r.code,name:r.name,before:old.status,after:r.status}]:[];});}
export function relaxations(data,plan,scenario){return plan.conditions.map(c=>{let next=structuredClone(plan);const step=['pb','pe'].includes(c.field)?2:c.field==='cfo'?10:5;const value=c.op.includes('>')?c.value-step:c.op.includes('<')?c.value+step:c.value;next.conditions=next.conditions.map(x=>x.id===c.id?{...x,value}:x);try{return {id:c.id,label:metricDefs[c.field].label,from:c.value,to:value,op:c.op,result:screen(data,next,scenario)};}catch{return null;}}).filter(Boolean);}
export function validateProposal(x,text){
 if(!x||x.logic!=='AND'||!Number.isInteger(x.window)||x.window<10||x.window>64||!Array.isArray(x.conditions)||x.conditions.length>12||!Array.isArray(x.unsupported)||x.unsupported.length>8)throw new Error('模型条件结构无效');
 const conditions=x.conditions.map((c,i)=>{if(!metricDefs[c.field]||!(['>=','<=','>','<','='].includes(c.op)||(c.value===null&&c.op===null))||typeof c.quote!=='string'||!c.quote||!text.includes(c.quote)||c.quote.length>160)throw new Error('模型字段或引用无效');const explicit=c.value!==null;if(explicit&&(!Number.isFinite(c.value)||!(c.quote.match(/-?\d+(?:\.\d+)?/g)||[]).map(Number).includes(c.value)))throw new Error('模型不得自行编造阈值');return {id:'c'+i,field:c.field,op:explicit?c.op:metricDefs[c.field].op,value:explicit?c.value:metricDefs[c.field].preset,assumption:!explicit,quote:c.quote};});
 if(x.unsupported.some(q=>typeof q!=='string'||!q||q.length>160||!text.includes(q)))throw new Error('不支持项必须引用原意图');
 if(x.window!==60&&!(text.match(/\d+/g)||[]).map(Number).includes(x.window))throw new Error('模型不得自行更改窗口');
 if(!conditions.length&&!x.unsupported.length)throw new Error('没有识别到可执行条件');return {logic:'AND',window:x.window,conditions,unsupported:x.unsupported};
}
