'use client';
import {useEffect,useState} from 'react';
import {ArrowLeft,ArrowUpRight,Bell,Check,Clock3,FileText,GitBranch,Layers3,LoaderCircle,Search,ShieldCheck,Sparkles,X} from 'lucide-react';
import './events.css';
import {identify} from '@/lib/events.mjs';
type Doc={id:string;title:string;company:string;anchor:string;kind:string;weight:number;verified:boolean;simulation?:boolean;source:string;url:string|null;page:number;announcement:string;occurredAt:string|null;disclosedAt:string;collectedAt:string|null;fetchedAt:string;timePrecision:string;note:string;sha256?:string;quote?:string;validUntil?:string;claimPages?:Record<string,number>;claims:Record<string,string>;evidenceStatus:string};
type Diff={field:string;before:string;after:string;evidenceIds:string[]};
type Event={id:string;company:string;eventType:string;anchor:string;first:string;earliestSourceId:string;status:string;conclusion:string;conflict:boolean;fields:Record<string,{value:string;ids:string[];conflict:boolean}>;evidence:Doc[]};
type Version={id:number;eventId:string;sourceId:string;at:string;diff:Diff[];summary:string;snapshot:Event};
type Notice={id:string;title:string;at:string;version:number;read:boolean;diff:Diff[]};
type State={revision:number;watch:boolean;asOf:string|null;events:Event[];docs:Doc[];catalog:Doc[];versions:Version[];notifications:Notice[];mode:string};
type Extract={company:string;eventType:string;anchor:string|null;kind:string;quote:string;summary:string};
const example='贵州茅台（600519）原始回购方案披露日为2024-09-21。本评论认为，回购若完成或改善每股指标，但尚不能证明经营需求改善。';
const fmt=(v:string|null|undefined)=>v?(/T/.test(v)?new Date(v).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false})+' CST':v):'未披露／未知';
export default function Events(){
 const [mode,setMode]=useState('verified'),[s,setS]=useState<State|null>(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[eid,setEid]=useState(''),[tab,setTab]=useState('时间线'),[focus,setFocus]=useState<Doc|null>(null),[version,setVersion]=useState<Version|null>(null),[text,setText]=useState(example),[extract,setExtract]=useState<Extract|null>(null),[ai,setAI]=useState(''),[notices,setNotices]=useState(false),[filter,setFilter]=useState('全部');
 async function readResponse(r:Response){if(!r.headers.get('content-type')?.includes('application/json'))throw Error('服务暂时不可用，请重试；上一版证据仍保留。');return r.json();}
 const current=s?.events.find(e=>e.id===eid)||s?.events[0];const viewed=version?.snapshot||current;
 async function load(m=mode){setError('');try{const r=await fetch(`/api/events?mode=${m}`);const x=await readResponse(r) as State & {error?:string};if(!r.ok)throw Error(x.error);setS(x);}catch(e){setError(e instanceof Error?e.message:'网络失败');}}
 useEffect(()=>{setS(null);setEid('');setVersion(null);setFocus(null);setMessage('');setExtract(null);setNotices(false);load(mode);},[mode]);
 async function act(action:string,extra:Record<string,unknown>={}){if(!s)return;setBusy(true);setError('');setMessage('');try{const r=await fetch(`/api/events?mode=${mode}`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,revision:s.revision,...extra})});const x=await readResponse(r) as State & {error?:string;duplicate?:boolean};if(!r.ok){if(r.status===409)await load();throw Error(x.error);}setS(x);setVersion(null);setMessage(x.duplicate?'重复证据已拦截：没有新增版本或重复通知。':action==='ingest'?'材料已归档；结论按披露时间重新计算。':action==='custom'?'已作为未核验材料保存，未提高事实权重。':'已保存。');}catch(e){setError(e instanceof Error?e.message:'请求失败，上一版保留。');}finally{setBusy(false);}}
 async function analyze(){setBusy(true);setError('');setExtract(null);setAI('');try{const r=await fetch('/api/events/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const x=await readResponse(r) as {error?:string;extracted:Extract;model:string;message:string};if(!r.ok)throw Error(x.error);setExtract(x.extracted);setAI(`实时 AI · ${x.model} · ${x.message}`);}catch(e){setError(e instanceof Error?e.message:'模型调用失败');}finally{setBusy(false);}}
 const pending=s?.catalog.filter(d=>!s.docs.some(x=>x.id===d.id))||[];const unread=s?.notifications.filter(n=>!n.read).length||0;
 const openEvidence=(id:string)=>{const d=viewed?.evidence.find(d=>d.id===id)||s?.events.flatMap(e=>e.evidence).find(d=>d.id===id);if(d)setFocus(d);};
 function download(){if(!s)return;const blob=new Blob([JSON.stringify({...s,exportedAt:new Date().toISOString()},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`event-evidence-${mode}.json`;a.click();URL.revokeObjectURL(url);}
 return <div className="event-app"><header className="event-header"><a href="/" className="event-brand"><Layers3 size={25}/><strong>知衡</strong><span>证据研究工作台</span></a><nav><a href="/">个股诊断</a><a className="active" href="/events">事件情报</a><span title="第三题待实现">意图选股 · 待接入</span></nav><button onClick={()=>setNotices(!notices)} className="notice-button"><Bell size={17}/> 通知 {unread>0&&<b>{unread}</b>}</button></header>
 <main className="event-main"><div className="event-breadcrumb"><a href="/">研究工作台</a> / 事件情报与证据时间线</div><section className="event-intro"><div><div className="eyebrow">EVENT INTELLIGENCE / 02</div><h1>追踪事实，理解变化。</h1><p>把分散材料串成同一事件，沿每一次变化回到原始证据。</p></div><div className="mode-switch"><button className={mode==='verified'?'selected':''} onClick={()=>setMode('verified')}>真实公告案例</button><button className={mode==='sandbox'?'selected':''} onClick={()=>setMode('sandbox')}>隔离演练区</button></div></section>
 {mode==='sandbox'?<div className="event-banner amber"><ShieldCheck size={18}/><div><b>模拟数据，不涉及现实上市公司。</b> 在此验证传闻、否认、更正、冲突与过期；状态和通知与真实案例隔离。评估时点：{s?.asOf||'尚未推进'}。</div></div>:<div className="event-banner"><ShieldCheck size={18}/><div><b>历史证据包 · 贵州茅台 2024 回购计划</b> 公告人工核验，非实时资讯。按顺序导入或故意乱序导入，观察版本如何变化。仅覆盖五个关键节点。</div></div>}
 {error&&<div role="alert" className="event-error">{error}<button onClick={()=>load()}>重新加载</button></div>}{message&&<div role="status" className="event-message">{message}</div>}
 {!s?<div className="event-loading"><LoaderCircle className="spin"/>正在读取证据工作区…</div>:<div className="event-grid"><aside className="event-sidebar"><section className="event-panel"><div className="panel-title"><h2>事件集合</h2><span>{s.events.length}</span></div>{s.events.length===0&&<p className="muted">尚无事件，导入下方材料开始演练。</p>}{s.events.map(e=><button key={e.id} className={`event-item ${current?.id===e.id?'chosen':''}`} onClick={()=>{setEid(e.id);setVersion(null);}}><small>{e.company==='600519'?'贵州茅台 · 600519':'演练标的 · '+e.company}</small><b>{e.eventType} · {e.anchor} 方案</b><span>{e.status}</span></button>)}<div className="event-rule"><GitBranch size={16}/><p>标的 + 事件类型 + 原始方案日期<br/>同一标的的新计划另建事件；缺少锚点先复核。</p></div></section>
 <section className="event-panel inbox"><div className="panel-title"><h2>材料收件箱</h2><span>{pending.length} 待处理</span></div><p className="muted">每次导入都会保留原证据，生成可比较版本。</p>{pending.map(d=><article key={d.id}><div><span className={`kind kind-${d.kind}`}>{d.kind}</span><small>{d.id} · {d.disclosedAt}</small></div><b>{d.title}</b><button disabled={busy} onClick={()=>act('ingest',{id:d.id})}>识别并归档 <ArrowUpRight size={14}/></button></article>)}{pending.length===0&&<p className="muted">本证据包已全部归档。</p>}{s.docs[0]&&<button className="text-button" disabled={busy} onClick={()=>act('ingest',{id:s.docs.find(d=>!d.id.startsWith('U-'))?.id})}>验证重复材料拦截</button>}{mode==='sandbox'&&<button disabled={busy} className="expiry-button" onClick={()=>act('expire',{asOf:'2026-01-06'})}><Clock3 size={15}/> 推进演练时钟至 01-06</button>}</section></aside>
 <div className="event-content">{viewed&&<><section className="event-panel event-summary"><div className="summary-heading"><div><div className="eyebrow">{viewed.company==='600519'?'600519.SH / 贵州茅台':'SIMULATION / 演练标的'}</div><h2>{viewed.anchor} {viewed.eventType}计划</h2><span className={`event-state ${viewed.conflict?'conflict':''}`}>{viewed.status}</span>{version&&<span className="history-tag">历史版本 V{version.id}<button onClick={()=>setVersion(null)}>返回当前</button></span>}</div><button className={`watch-button ${s.watch?'watching':''}`} disabled={busy} onClick={()=>act('watch',{value:!s.watch})}><Bell size={16}/>{s.watch?'已关注变化':'关注变化'}</button></div><p>{viewed.conclusion}</p><div className="summary-metrics"><div><small>最早已收录来源</small><button onClick={()=>openEvidence(viewed.earliestSourceId)}>{viewed.first} · {viewed.earliestSourceId}</button></div><div><small>证据规模</small><b>{viewed.evidence.length} 份 · {viewed.evidence.filter(d=>d.verified).length} 份已核验</b></div><div><small>工作区更新时间</small><b>{fmt(s.versions.at(-1)?.at)}</b></div></div><div className="claim-grid">{Object.entries(viewed.fields).map(([k,v])=><div key={k}><small>{k}</small><strong>{v.value}</strong><span>{v.ids.map(id=><button key={id} onClick={()=>openEvidence(id)}>{id} ↗</button>)}</span></div>)}</div><div className="relationship"><b>与关注标的的关系 · {viewed.company==='600519'?'直接主体':'演练关系'}</b><p>{viewed.company==='600519'?'回购涉及公司资金使用与潜在股本变化，值得回到财务和每股指标核验。回购完成不等于需求改善，也不能证明股价变化由其导致。':'只用于研究状态演化，不映射真实投资对象。'}</p>{viewed.company==='600519'&&<a href="/?research=buyback">继续核验：资金与股本 → 个股诊断 <ArrowUpRight size={14}/></a>}</div></section>
 <section className="event-panel"><div className="event-tabs">{['时间线','版本比较','证据分层'].map(t=><button key={t} className={tab===t?'on':''} onClick={()=>setTab(t)}>{t}</button>)}<button className="event-export" onClick={download}>导出证据包</button></div>
 {tab==='时间线'&&<div className="timeline">{viewed.evidence.filter(d=>filter==='全部'||d.kind===filter).map(d=><article key={d.id}><div className="timeline-dot"/><div className="timeline-date">披露 {d.disclosedAt}<small>发生 {d.occurredAt||'未知'}</small></div><div className="timeline-body"><div><span className={`kind kind-${d.kind}`}>{d.kind}</span><span className="muted">{d.id} · {d.evidenceStatus}</span></div><button className="source-title" onClick={()=>setFocus(d)}>{d.title} <ArrowUpRight size={16}/></button><p>{Object.entries(d.claims).map(([k,v])=>`${k}：${v}`).join('；')}</p><small>{d.source} · 证据权重 {d.weight}/5</small><div className="timeline-footer"><span>抓取/入库 {fmt(d.fetchedAt)}</span><button onClick={()=>setFocus(d)}>查看四类时间与原始凭据</button></div></div></article>)}</div>}
 {tab==='版本比较'&&<div className="versions">{s.versions.filter(v=>v.eventId===viewed.id).slice().reverse().map(v=><article key={v.id}><div className="version-heading"><b>V{v.id} · {v.summary}</b><button onClick={()=>{setVersion(v);setTab('时间线');}}>查看这一版</button></div><small>{fmt(v.at)} · {v.sourceId==='expiry'?'时效评估':v.sourceId}</small>{v.diff.length?v.diff.map((d,i)=><div className="diff-row" key={i}><b>{d.field}</b><span>{d.before}</span><strong>→ {d.after}</strong><small>{d.evidenceIds.join(' · ')}</small></div>):<p className="muted">新增证据未改变当前事实或状态，保留归档记录，不重复通知。</p>}</article>)}</div>}
 {tab==='证据分层'&&<div className="layers"><p>权重是可解释的研究优先级，<b>不是真实性概率</b>。只有已核验事实参与确认字段；同日冲突保留双方。</p><div className="layer-grid">{[['事实','5','可验证陈述；仍需核验来源'],['观点','2','对已知事实的评价'],['推测','1','条件性假设或因果判断'],['传闻','0','缺乏可核验的原始凭据']].map(([k,w,t])=><div key={k}><span className={`kind kind-${k}`}>{k}</span><h3>{w}<small>/5</small></h3><p>{t}</p></div>)}</div><p className="muted">用户提交即使分类为“事实”，核验前权重仍为零；同一文件哈希去重，同源转载不增加独立支持。历史数值随披露时间更新，不按抓取顺序覆盖。</p><div className="filter-chips">{['全部','事实','观点','推测','传闻'].map(f=><button className={filter===f?'selected':''} key={f} onClick={()=>setFilter(f)}>{f}</button>)}</div>{viewed.evidence.filter(d=>filter==='全部'||d.kind===filter).map(d=><button className="evidence-row" key={d.id} onClick={()=>setFocus(d)}><span>{d.id} · {d.kind}</span><b>{d.title}</b><span>{d.evidenceStatus} ↗</span></button>)}</div>}
 </section></>}
 <section className="event-panel ai-import"><div className="panel-title"><h2><Sparkles size={19}/> 让 AI 整理一段新材料</h2><span>先提取，再确认归档</span></div><p className="muted">粘贴公告摘录、评论或传闻。AI 提议事件归属与语义类型，你可修改；未经来源核验的内容始终保留为待核验。</p><textarea aria-label="事件材料" value={text} onChange={e=>{setText(e.target.value);setExtract(null);}} maxLength={4500}/><div className="ai-actions"><small>仅文本提取，不自动抓取任意 URL · 材料将发往 OpenRouter 处理</small><button disabled={busy} onClick={analyze}>{busy?<LoaderCircle className="spin" size={16}/>:<Sparkles size={16}/>} AI 识别事件</button></div>
 {extract&&<div className="extraction"><p className="muted">{ai}</p><div className="extract-fields"><label>标的代码<input value={extract.company} onChange={e=>setExtract({...extract,company:e.target.value})}/></label><label>事件类型<select value={extract.eventType} onChange={e=>setExtract({...extract,eventType:e.target.value})}>{['回购','扩建','其他'].map(k=><option key={k}>{k}</option>)}</select></label><label>原始方案日期<input type="date" value={extract.anchor||''} onChange={e=>setExtract({...extract,anchor:e.target.value})}/></label><label>语义类别<select value={extract.kind} onChange={e=>setExtract({...extract,kind:e.target.value})}>{['事实','观点','推测','传闻'].map(k=><option key={k}>{k}</option>)}</select></label></div><label>摘要<input value={extract.summary} onChange={e=>setExtract({...extract,summary:e.target.value})}/></label><blockquote>{extract.quote}</blockquote><div className="merge-decision"><GitBranch size={17}/>{identify(extract,s.events).reason}</div><button disabled={busy||!extract.anchor} onClick={()=>act('custom',{doc:extract})}>确认归档 · 保持未核验</button></div>}
 </section><p className="event-footnote">本产品用于证据研究，不提供买卖建议。刷新可恢复本浏览器工作区；隐私窗口和不同浏览器相互独立。站内通知仅在手动导入或演练时触发，尚无后台抓取与主动推送。</p></div></div>}
 </main>
 {notices&&<div className="notice-panel"><div className="panel-title"><h2>结论变化通知</h2><button aria-label="关闭通知" onClick={()=>setNotices(false)}><X size={20}/></button></div><p className="muted">关注期间的实质变化才通知，重复材料不重复提醒。</p>{s?.notifications.length===0&&<p>暂无变化通知。</p>}{s?.notifications.map(n=><article key={n.id} className={n.read?'read':''}><b>{n.title}</b><small>{fmt(n.at)} · V{n.version}</small>{n.diff.map((d,i)=><p key={i}>{d.field}：{d.before} → {d.after}</p>)}<button onClick={()=>{const v=s.versions.find(v=>v.id===n.version);if(v){setEid(v.eventId);setVersion(v);setTab('版本比较');}if(!n.read)act('read',{id:n.id});setNotices(false);}}>查看变化并标记已读</button></article>)}</div>}
 {focus&&<div className="event-overlay" onClick={()=>setFocus(null)}><aside className="event-drawer" role="dialog" aria-modal="true" aria-label="原始证据" onClick={e=>e.stopPropagation()}><div className="panel-title"><span className={`kind kind-${focus.kind}`}>{focus.kind} · {focus.id}</span><button aria-label="关闭证据" onClick={()=>setFocus(null)}><X/></button></div><h2>{focus.title}</h2><p>{focus.source} · {focus.announcement}</p><div className="drawer-times">{[['事件发生时间',focus.occurredAt],['披露时间',focus.disclosedAt],...(focus.validUntil?[["证据有效期至",focus.validUntil]]:[]),['资料采集时间',focus.collectedAt],['本工作区抓取/入库时间',focus.fetchedAt],['结论更新时间',s?.versions.filter(v=>v.sourceId===focus.id).at(-1)?.at]].map(([k,v])=><div key={k}><small>{k}</small><b>{fmt(v)}</b></div>)}</div><p className="muted">{focus.timePrecision||'日精度；未披露具体时分秒。入库、更新时间为中国标准时间展示，UTC存储。'}</p><h3>逐项凭据</h3>{Object.entries(focus.claims).map(([k,v])=><div className="drawer-claim" key={k}><small>{k}{focus.url&&<a className="claim-page" href={`${focus.url}#page=${focus.claimPages?.[k]||focus.page}`} target="_blank" rel="noopener noreferrer"> · 原文第{focus.claimPages?.[k]||focus.page}页 ↗</a>}</small><b>{v}</b></div>)}{focus.quote&&<blockquote>{focus.quote}</blockquote>}<div className="event-banner amber">{focus.note}</div><p>核验状态：{focus.verified?'已核验（模拟区只代表演练设定）':'尚未核验'}<br/>证据权重：{focus.weight}/5 · {focus.evidenceStatus||'有效'}</p>{focus.url&&<a className="original-link" href={`${focus.url}#page=${focus.page}`} target="_blank" rel="noopener noreferrer"><FileText size={17}/> 打开公告原文 · 第{focus.page}页 <ArrowUpRight size={16}/></a>}{focus.sha256&&<p className="hash">文件 SHA-256<br/>{focus.sha256}</p>}<p className="muted">原始资料不因后续更正被删除。真实案例为历史回放，尚未持续监测新的公司披露。</p></aside></div>}
 </div>;
}
